#Database
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/aws_practice
    username: postgres
    password: admin
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc:
          time_zone: UTC
          lob:
            non_contextual_creation: true

#server
server:
  port: 8080